// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/2f4ek/lets-go-chat/database"
	"github.com/2f4ek/lets-go-chat/internal/chatModels"
	"github.com/2f4ek/lets-go-chat/internal/handlers"
	"github.com/2f4ek/lets-go-chat/internal/repositories"
	"github.com/2f4ek/lets-go-chat/internal/router"
)

// Injectors from wire.go:

func InitializeRouter() (router.Router, error) {
	userRepository := repositories.ProvideUserRepository()
	databaseDatabase := database.ProvideDatabase()
	chatMessageRepository := repositories.ProvideChatMessageRepository(databaseDatabase)
	chat := chatModels.ProvideChat(userRepository, chatMessageRepository)
	chatHandler := handlers.ProvideChatHandler(userRepository, chat)
	registerHandler := handlers.ProvideRegisterHandler(userRepository)
	authHandler := handlers.ProvideAuthHandler(userRepository)
	routerRouter := router.ProvideRouter(chatHandler, registerHandler, authHandler)
	return routerRouter, nil
}

func InitializeChat() (*handlers.ChatHandler, error) {
	userRepository := repositories.ProvideUserRepository()
	databaseDatabase := database.ProvideDatabase()
	chatMessageRepository := repositories.ProvideChatMessageRepository(databaseDatabase)
	chat := chatModels.ProvideChat(userRepository, chatMessageRepository)
	chatHandler := handlers.ProvideChatHandler(userRepository, chat)
	return chatHandler, nil
}
